apiVersion: v1
kind: Service
metadata:
  name: etcd-service
  namespace: kube-system
  # This alpha annotation will retain the endpoints even if the etcd pod isn't ready.
  # This feature is always enabled in endpoint controller in k8s even it is alpha.
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  selector:
    app: etcd
    etcd_cluster: kube-etcd
  clusterIP: ${etcd_service_ip}
  ports:
  - name: client
    port: 2379
    protocol: TCP
