apiVersion: v1
data:
  apiserver.crt: "${apiserver_crt_b64}"
  apiserver.key: "${apiserver_key_b64}"
  aggregator.crt: "${api_aggregator_crt_b64}"
  aggregator.key: "${api_aggregator_key_b64}"
  ca.crt: "${apiserver_ca_crt_b64}"
  etcd-client-ca.crt: "${etcd_client_ca_crt_b64}"
  etcd-client.crt: "${etcd_client_crt_b64}"
  etcd-client.key: "${etcd_client_key_b64}"
  service-account.pub: ${service_account_pub_b64}
kind: Secret
metadata:
  name: kube-apiserver
  namespace: kube-system
type: Opaque
